### ISSUE TITLE
Picked up collectibles remain visible for one frame when level is loaded

### ISSUE THREAD

**Issue by isaaccp** [KoBeWi/Metroidvania-System#19]
This is not very evident in the sample project included with MetSys as the level is not reloaded on death, but on my game I reload level on death and it makes it very obvious.

The problem is that when loading the level and registering the object, the stored callback does a queue_free() which doesn't take effect until the next frame, leaving the object visible.

This is my quick fix for my project (if object is CanvasItem, I set visible = false and call queue_free()):
![image](https://github.com/KoBeWi/Metroidvania-System/assets/8712/e8c6b9e0-d8c0-4c02-9360-b9a53a010da3)
but maybe can use a lambda instead.

**Comment by isaaccp** [comment]
I think it looks better/easier:
![image](https://github.com/KoBeWi/Metroidvania-System/assets/8712/be0a624b-a657-461a-bb19-cfb55a8892a9)

**Comment by KoBeWi** [comment]
> doesn't take effect until the next frame

It does take effect at the end of the same frame. I did test it extensively and couldn't reproduce this problem, the object is not visible unless you register it at some weird moment (I'd be interested to see the project).

My original solution to the problem was making the method return `bool`, so your code would be
```GDScript
if register_storable_object():
	hide()
```
but since I couldn't find a case when this is useful, I decided not to add it.

**Comment by KoBeWi** [comment]
Ok found it:
```GDScript
await get_tree().create_timer(0.2).timeout
Game.get_player().kill()
```
And I was right saying
> unless you register it at some weird moment

This is a tricky case, because you won't know it without knowing the engine source code, but timers are processed after queued nodes are freed. Which means that the next freeing won't happen until next available frame, resulting in the object being drawn.
https://github.com/godotengine/godot/blob/d76c1d0e516fedc535a2e394ab780cac79203477/scene/main/scene_tree.cpp#L516-L522
tbh this looks like engine bug, because this only happens in process frame. Physics frame does cleanup the queue after timers.

Which means that you can "fix" this by using:
```GDScript
await get_tree().create_timer(0.2, false, true).timeout
```
This makes the timer processed during physics frame and avoids the issue.

**Comment by isaaccp** [comment]
Thanks for the thorough explanation, issue opened and workaround!
