### ISSUE TITLE
Backport for Godot 3.5

### ISSUE THREAD

**Issue by PPBoxHead** [KoBeWi/Metroidvania-System#59]
Hello, I was wondering if a backport to 3.5 or 3.6 versions would be to hardful to make and what kind of 4.x dependencies this addons rely on to give it a try myself in case it's possible.
(Sorry my english)

**Comment by KoBeWi** [comment]
Here's a (likely non-exhaustive) list of used features that don't exist in 3.x:
- Vector2/Vector3i
- typed arrays
- Callables
- cyclic script dependencies (I assume there are some)
- static variables
- PROCESS_MODE_DISABLED
- `_validate_property()`
- EditorResourcePicker
- Resource UIDs
- `@export_group`

I think all of them have some (worse) equivalents or workarounds in Godot 3, but obviously replacing all that is going to be lots of work and will result in much less type-safe and less robust code. Porting an earlier version of the addon could be easier, due to less complexity. So while it's not impossible, I'd advise against doing that.

**Comment by KoBeWi** [comment]
Closing as it's not planned. Feel free to still discuss it though.
